name: Lint

on:
  push:
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Lint robot code
        run: ./gradlew spotlessCheck